### ISSUE TITLE
Global Filebrowser crashing on some Servers

### ISSUE THREAD

**Issue by Snovna** [Cloudbreaker-Plugins/IssueTracker#3]
Plugin gives me error when joining some Teamspeak Servers and crashs. (Screenshot below)

OS: Windows 10 64bit
TS3Client: 3.2.5 [Stable] on Windows
Server Version with issue: 3.7.2 (Linux)
Official TS3 Public Server on version 3.7.0 (at time of reporting) works without problems

http://prntscr.com/nr0w96

[ts3dump_1558369496987.zip](https://github.com/Cloudbreaker-Plugins/IssueTracker/files/3198874/ts3dump_1558369496987.zip)

I don't know how to reproduce the issue, because I only get errors on some servers. hope this helps

**Comment by Cloudbreaker-Plugins** [comment]
Should be fixed with 0.8.0 on latest client version.
