### ISSUE TITLE
[Chatlog Viewer] Crash after exiting TeamSpeak or attempting to disable the plugin in the Options menu

### ISSUE THREAD

**Issue by BradyThe** [Cloudbreaker-Plugins/IssueTracker#4]
- **Client Version:** 3.3.0 (01.06.2019 23:11:43)
- **Qt Version:** 5.12.3
- **Branch:** Beta
- **Plugin Version:** 1.0.0.2
- **Operating System:** Windows 10 Pro 1803 17134.765
- **Architecture:** 64-bit
- **Reproduction:** Disable the plugin from within TeamSpeak, or exit the program
- **Crash dump:**
Exiting: [ts3dump_1559577500170_EXIT.zip](https://github.com/Cloudbreaker-Plugins/IssueTracker/files/3248493/ts3dump_1559577500170_EXIT.zip)
Disabling: [ts3dump_1559577532810_DISABLE.zip](https://github.com/Cloudbreaker-Plugins/IssueTracker/files/3248495/ts3dump_1559577532810_DISABLE.zip)

**Comment by Cloudbreaker-Plugins** [comment]
Thanks, will be fixed with next update.
